name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this as necessary

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Adjust this as necessary

      - name: Install Dependencies
        run: npm install
        working-directory: frontend

      - name: Inject Environment Variables
        run: |
          echo "REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }}" >> $GITHUB_ENV
          echo "REACT_APP_TENANT_ID=${{ secrets.REACT_APP_TENANT_ID }}" >> $GITHUB_ENV

      - name: Build
        run: npm run build
        working-directory: frontend
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          REACT_APP_TENANT_ID: ${{ secrets.REACT_APP_TENANT_ID }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages  # Branch to deploy to
          folder: frontend/build  # Folder to deploy
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensure this is correct
