name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this as necessary

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Adjust this as necessary

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages  # Branch to deploy to
          folder: build  # Folder to deploy
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensure this is correct
